
import React, { useState, useEffect } from 'react';
import { db } from '../services/db';
import { Expenditure } from '../types';
import { Printer, FileSpreadsheet } from 'lucide-react';

export const ExpenditureReport = () => {
  const [list, setList] = useState<Expenditure[]>([]);

  useEffect(() => {
    db.getExpenditure().then(setList);
  }, []);

  const total = list.reduce((acc, curr) => acc + curr.amount, 0);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-white min-h-screen p-6">
      <div className="flex flex-col md:flex-row justify-between items-center mb-6 no-print bg-gray-50 p-4 rounded border">
        <div>
            <h2 className="text-2xl font-bold text-gray-800 flex items-center gap-2">
                <FileSpreadsheet className="text-green-600" /> Expenditure Report
            </h2>
            <p className="text-gray-500 text-sm">View and print financial records</p>
        </div>
        <button 
            onClick={handlePrint} 
            className="mt-4 md:mt-0 bg-gray-800 text-white px-6 py-2 rounded shadow hover:bg-black flex items-center gap-2 transition-colors"
        >
            <Printer size={18} /> Print Report
        </button>
      </div>

      <div className="printable-area bg-white">
        <div className="hidden print:block text-center border-b-2 border-black pb-4 mb-6">
            <h1 className="text-3xl font-extrabold uppercase">XYZ Company</h1>
            <p className="text-lg font-semibold">Khuba Plot</p>
            <h2 className="text-xl font-bold uppercase mt-4 border-t border-gray-300 pt-2 inline-block">Expenditure Statement</h2>
        </div>

        <div className="overflow-x-auto print:overflow-visible">
            <table className="w-full text-sm text-left border-collapse border border-gray-300">
                <thead className="bg-red-50 text-red-900 uppercase text-xs print:bg-gray-200 print:text-black">
                    <tr>
                        <th className="p-3 border border-gray-300 w-32">Date</th>
                        <th className="p-3 border border-gray-300 font-bold">Head Name</th>
                        <th className="p-3 border border-gray-300">Particulars</th>
                        <th className="p-3 border border-gray-300 text-center w-24">Type</th>
                        <th className="p-3 border border-gray-300 text-right w-32">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {list.length === 0 && (
                        <tr><td colSpan={5} className="p-6 text-center text-gray-400 italic">No expenditure records found.</td></tr>
                    )}
                    {list.map((l) => (
                        <tr key={l.id} className="hover:bg-gray-50 border-b border-gray-300">
                            <td className="p-3 border border-gray-300">{l.date}</td>
                            <td className="p-3 border border-gray-300 font-semibold text-gray-800">{l.headName}</td>
                            <td className="p-3 border border-gray-300 text-gray-600">{l.particulars}</td>
                            <td className="p-3 border border-gray-300 text-center text-xs font-medium">{l.paymentType}</td>
                            <td className="p-3 border border-gray-300 text-right font-bold text-gray-900">₹{l.amount.toFixed(2)}</td>
                        </tr>
                    ))}
                </tbody>
                <tfoot>
                    <tr className="bg-gray-100 font-bold border-t-2 border-gray-400 text-lg print:bg-gray-200">
                        <td colSpan={4} className="p-4 border border-gray-300 text-right">Total Expenditure:</td>
                        <td className="p-4 border border-gray-300 text-right text-red-700 print:text-black">₹{total.toFixed(2)}</td>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div className="mt-16 hidden print:flex justify-between text-sm pt-8">
            <div className="text-center">
                <div className="w-48 border-b border-black mb-2"></div>
                <p className="font-semibold">Accountant Signature</p>
            </div>
            <div className="text-center">
                <div className="w-48 border-b border-black mb-2"></div>
                <p className="font-semibold">Manager Signature</p>
            </div>
        </div>
        
        <div className="mt-8 text-center text-[10px] text-gray-400 hidden print:block">
             Generated by AgriSmart Farm Management System | {new Date().toLocaleString()}
        </div>
      </div>
    </div>
  );
};
